# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucena/Desktop/uni/3ano2sem/CG/Trabalho/CG-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucena/Desktop/uni/3ano2sem/CG/Trabalho/CG-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucena/Desktop/uni/3ano2sem/CG/Trabalho/CG-Project/CMakeFiles /home/lucena/Desktop/uni/3ano2sem/CG/Trabalho/CG-Project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucena/Desktop/uni/3ano2sem/CG/Trabalho/CG-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generator

# Build rule for target.
generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generator
.PHONY : generator

# fast build rule for target.
generator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/build
.PHONY : generator/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

engine.o: engine.cpp.o
.PHONY : engine.o

# target to build an object file
engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cpp.o
.PHONY : engine.cpp.o

engine.i: engine.cpp.i
.PHONY : engine.i

# target to preprocess a source file
engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cpp.i
.PHONY : engine.cpp.i

engine.s: engine.cpp.s
.PHONY : engine.s

# target to generate assembly for a file
engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cpp.s
.PHONY : engine.cpp.s

fpsCamera.o: fpsCamera.cpp.o
.PHONY : fpsCamera.o

# target to build an object file
fpsCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/fpsCamera.cpp.o
.PHONY : fpsCamera.cpp.o

fpsCamera.i: fpsCamera.cpp.i
.PHONY : fpsCamera.i

# target to preprocess a source file
fpsCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/fpsCamera.cpp.i
.PHONY : fpsCamera.cpp.i

fpsCamera.s: fpsCamera.cpp.s
.PHONY : fpsCamera.s

# target to generate assembly for a file
fpsCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/fpsCamera.cpp.s
.PHONY : fpsCamera.cpp.s

generator.o: generator.cpp.o
.PHONY : generator.o

# target to build an object file
generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/generator.cpp.o
.PHONY : generator.cpp.o

generator.i: generator.cpp.i
.PHONY : generator.i

# target to preprocess a source file
generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/generator.cpp.i
.PHONY : generator.cpp.i

generator.s: generator.cpp.s
.PHONY : generator.s

# target to generate assembly for a file
generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/generator.cpp.s
.PHONY : generator.cpp.s

lights.o: lights.cpp.o
.PHONY : lights.o

# target to build an object file
lights.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lights.cpp.o
.PHONY : lights.cpp.o

lights.i: lights.cpp.i
.PHONY : lights.i

# target to preprocess a source file
lights.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lights.cpp.i
.PHONY : lights.cpp.i

lights.s: lights.cpp.s
.PHONY : lights.s

# target to generate assembly for a file
lights.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lights.cpp.s
.PHONY : lights.cpp.s

model.o: model.cpp.o
.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i
.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s
.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/model.cpp.s
.PHONY : model.cpp.s

ponto.o: ponto.cpp.o
.PHONY : ponto.o

# target to build an object file
ponto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/ponto.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/ponto.cpp.o
.PHONY : ponto.cpp.o

ponto.i: ponto.cpp.i
.PHONY : ponto.i

# target to preprocess a source file
ponto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/ponto.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/ponto.cpp.i
.PHONY : ponto.cpp.i

ponto.s: ponto.cpp.s
.PHONY : ponto.s

# target to generate assembly for a file
ponto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/ponto.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/ponto.cpp.s
.PHONY : ponto.cpp.s

tinyxml2/tinyxml2.o: tinyxml2/tinyxml2.cpp.o
.PHONY : tinyxml2/tinyxml2.o

# target to build an object file
tinyxml2/tinyxml2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/tinyxml2/tinyxml2.cpp.o
.PHONY : tinyxml2/tinyxml2.cpp.o

tinyxml2/tinyxml2.i: tinyxml2/tinyxml2.cpp.i
.PHONY : tinyxml2/tinyxml2.i

# target to preprocess a source file
tinyxml2/tinyxml2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/tinyxml2/tinyxml2.cpp.i
.PHONY : tinyxml2/tinyxml2.cpp.i

tinyxml2/tinyxml2.s: tinyxml2/tinyxml2.cpp.s
.PHONY : tinyxml2/tinyxml2.s

# target to generate assembly for a file
tinyxml2/tinyxml2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/tinyxml2/tinyxml2.cpp.s
.PHONY : tinyxml2/tinyxml2.cpp.s

transformations.o: transformations.cpp.o
.PHONY : transformations.o

# target to build an object file
transformations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/transformations.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/transformations.cpp.o
.PHONY : transformations.cpp.o

transformations.i: transformations.cpp.i
.PHONY : transformations.i

# target to preprocess a source file
transformations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/transformations.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/transformations.cpp.i
.PHONY : transformations.cpp.i

transformations.s: transformations.cpp.s
.PHONY : transformations.s

# target to generate assembly for a file
transformations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/transformations.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/transformations.cpp.s
.PHONY : transformations.cpp.s

vetores.o: vetores.cpp.o
.PHONY : vetores.o

# target to build an object file
vetores.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/vetores.cpp.o
.PHONY : vetores.cpp.o

vetores.i: vetores.cpp.i
.PHONY : vetores.i

# target to preprocess a source file
vetores.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/vetores.cpp.i
.PHONY : vetores.cpp.i

vetores.s: vetores.cpp.s
.PHONY : vetores.s

# target to generate assembly for a file
vetores.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/vetores.cpp.s
.PHONY : vetores.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... generator"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... fpsCamera.o"
	@echo "... fpsCamera.i"
	@echo "... fpsCamera.s"
	@echo "... generator.o"
	@echo "... generator.i"
	@echo "... generator.s"
	@echo "... lights.o"
	@echo "... lights.i"
	@echo "... lights.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... ponto.o"
	@echo "... ponto.i"
	@echo "... ponto.s"
	@echo "... tinyxml2/tinyxml2.o"
	@echo "... tinyxml2/tinyxml2.i"
	@echo "... tinyxml2/tinyxml2.s"
	@echo "... transformations.o"
	@echo "... transformations.i"
	@echo "... transformations.s"
	@echo "... vetores.o"
	@echo "... vetores.i"
	@echo "... vetores.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

